name: Build and Release Python Project

on:
  push:
    tags:
      - 'v*' # Triggers on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Use your desired Python version

      # Step 3: Install build dependencies
      - name: Install build tools
        run: pip install build --upgrade

      # Step 4: Build the project
      - name: Build the Python Project
        run: python -m build

      # Step 5: Create a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Upload all artifacts in the dist/ folder 
          files: |
            dist/* 